name: macOS

on:
  pull_request:
  push:
  schedule:
    - cron: '00 21 * * *'

jobs:
  general:
    runs-on: macOS-latest
    steps:
      - name: Checkout syslog-ng source
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew update --preinstall
          brew bundle --file=contrib/Brewfile

      - name: Set ENV variables
        run: |
          . .github/workflows/gh-tools.sh

          HOMEBREW_PREFIX="$(brew --prefix)"
          PYTHONUSERBASE="${HOME}/python_packages"
          PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/openssl@1.1/lib/pkgconfig:${HOMEBREW_PREFIX}/opt/net-snmp/lib/pkgconfig:${PKG_CONFIG_PATH}"
          CFLAGS="-I${HOMEBREW_PREFIX}/include/ ${CFLAGS}"
          LDFLAGS="-L${HOMEBREW_PREFIX}/lib ${LDFLAGS}"
          THREADS="$(sysctl -n hw.physicalcpu)"
          CONFIGURE_FLAGS="
            --with-ivykis=system
            --disable-sun-streams
            --disable-systemd
            --disable-pacct
            --disable-smtp
            --disable-mqtt
            --enable-all-modules
            --with-python=3
          "

          gh_export PYTHONUSERBASE PKG_CONFIG_PATH THREADS CONFIGURE_FLAGS CFLAGS LDFLAGS
          gh_path "${HOMEBREW_PREFIX}/bin:${HOMEBREW_PREFIX}/opt/bison/bin:${HOMEBREW_PREFIX}/opt/libnet/bin:${PYTHONUSERBASE}/bin:${HOMEBREW_PREFIX}/opt/net-snmp/bin:${PATH}"

          ln -s "${HOMEBREW_PREFIX}/bin/gcc-11" "${HOMEBREW_PREFIX}/bin/gcc"

      - name: autogen.sh
        run: |
          ./autogen.sh

      - name: configure
        run: |
          ./configure ${CONFIGURE_FLAGS}

      - name: make
        run: |
          set -e

          make --keep-going -j ${THREADS} || \
            { \
              S=$?; \
              make V=1; \
              return $S; \
            }

      - name: make check
        run: |
          set -e

          make --keep-going check -j ${THREADS} || \
            { \
              S=$?; \
              echo "Output of first test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              make V=1 check; \
              echo "Output of second test invocation:"; \
              find . -name test-suite.log | xargs cat; \
              return $S; \
            }
